schoolproject/schoolapp/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolapp import views
app_name='schoolapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('newpage',views.newpage,name='newpage'),
    path('form',views.form,name='form'),
    path('onclick',views.onclick,name='onclick'),
]

schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.

schoolproject/schoolapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse


# Create your views here.

def home(request):
    return render(request,"home.html")
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid")
    return render(request,"login.html")
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username already exist")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email already exist")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,password=password,email=email)
                user.save();
                return redirect('login')

        else:
            messages.info(request,"password not matching")
            return redirect('register')
        return redirect('/')
    return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')
def newpage(request):
    return render(request,"new_page.html")
def form(request):
    return render(request,"form.html")
def onclick(request):
    return render(request,"onclick.html")

schoolproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>School Site</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">ABC School</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a href="{% url 'schoolapp:login' %}"class="nav-link">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'schoolapp:register' %}">Register</a>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Department
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science">Science</a>
                        <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
                        <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">Humanities</a>
                        <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a>
                        <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Political_science">Political Science</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

{% block body %}

{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

schoolproject/templates/form.html
{% extends 'base.html' %}
{% block body %}
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
var subjectObject = {
  "Computer": {
    "B-Tech": ["None"],
    "MBBS": ["None"],
    "Architecture": ["None"]
  },
  "Commerce": {
    "BCom": ["None"],
    "BBA": ["None"],
    "CA" : ["None"]
  },
  "Humanities": {
    "BA Psychilogy": ["None"],
    "BA LLB": ["None"],
    "Journalism" : ["None"]
  },
  "Computer Science": {
    "BCA": ["None"],
    "Software Engineer": ["None"],
    "BSc in Computer Science" : ["None"]
  },
  "Political Science": {
    "Civil Services": ["None"],
    "Teaching": ["None"],
    "Law" : ["None"]
  }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");

  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x,x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns
   
    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y,y);
    }
  }

}
</script>
</head>
<body>
<div class="container">
  <h1>Application Form</h1>
  <form name="registration" class="registartion-form"  method="POST">
    {% csrf_token %}


    <table>
      <tr>
        <td><label for="name">Name:</label></td>
        <td><input type="text" name="name" id="name" ></td>
      </tr>
      <tr>
        <td><label for="dob">DOB:</label></td>
        <td><input type="date" name="dob" id="dob"></td>
      </tr>
      <tr>
        <td><label for="age">Age:</label></td>
        <td><input type="number" name="number" id="number" ></td>
      </tr>
      <tr>
        <td><label for="gender">Gender:</label></td>
        <td>Male: <input type="radio" name="gender" value="male">
          Female: <input type="radio" name="gender" value="female">
        </td>
      </tr>
      <tr>
        <td><label for="phoneNumber">Phone Number:</label></td>
        <td><input type="number" name="phoneNumber" id="phoneNumber"></td>
      </tr>
      <tr>
        <td><label for="email">Email:</label></td>
        <td><input type="text" name="email" id="email"></td>
      </tr>

      <tr>
        <td><label for="address">Address:</label></td>
        <td><textarea name="address" id="address" ></textarea></td>
      </tr>

      <tr>
        <td>Department: </td>
        <td><select name="subject" id="subject">
              <option value="" selected="selected">Select Department</option>
            </select>
        </td>

      <tr>
        <td>Course: </td>
        <td><select name="topic" id="topic">
              <option value="" selected="selected">Please select department first</option>
            </select>
        </td>
      </tr>


      </tr>


      <tr>
        <td><label for="Purpose">Purpose</label></td>
        <td>
          <select id="purpose" name="purpose">
            <option value="">Select</option>
            <option value="">For Enquiry</option>
            <option value="">Place Order</option>
            <option value="">Return</option>
          </select></td>
      </tr>
      <tr>
        <td><label for="material">Materials Provide :</label></td>
        <td>
          <input type="checkbox" id="debit" name="materials[]" value="Debit Note Book">
          <label for="debit">Debit Note Book</label>
          <input type="checkbox" id="pen" name="materials[]" value="Pen">
          <label for="debit">Pen</label>
          <input type="checkbox" id="papper" name="materials[]" value="Exam pappers">
          <label for="debit">Exam Pappers</label></td>
      </tr>
      <tr div class="button">
        <td colspan="2">
          <a href="{% url 'schoolapp:onclick' %}"
                class="btn btn-success " style="color:white;">Submit</a>
        </td>
        <td>
        <a href="{% url 'schoolapp:logout' %}"
                class="btn btn-success " style="color:white;">Logout</a>
        </td>
      </tr>

    </table>
  </form>

</div>

</body>
</html>

{% endblock %}

schoolproject/templates/home.html
{% extends 'base.html' %}
{%  load static %}
{% block body %}
    <div class="container">
        <div class="text-center">
            <h1>Welcome to ABC School</h1>
        </div>
    </div>
    <div>
        <img src="{% static 'images/school.jpg' %}" alt="" width="1500px" height="350px">
    </div>
    <div class="container" >
         <div class="vertical-center">
            <a  href="{% url 'schoolapp:login' %}"class="btn btn-warning" href="">Login</a>
         </div>

    </div>
{% endblock %}

schoolproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<section class="vh-100" xmlns="http://www.w3.org/1999/html">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="{% static 'images/login.jpg' %}" width="100%" height="100%" style="padding-top:20px;">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form action="login" method="post">
           {% csrf_token %}

          <!-- User input -->
          <div class="form-outline mb-4">
            <input type="email" id="form3Example3" class="form-control form-control-lg"
              placeholder="Enter User Name" />
            <label class="form-label" for="form3Example3">User Name</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" id="form3Example4" class="form-control form-control-lg"
              placeholder="Enter password" />
            <label class="form-label" for="form3Example4">Password</label>
          </div>
          <div class="text-center text-lg-start mt-4 pt-2">
            <a href="{% url 'schoolapp:newpage' %}"class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;">Submit</a><br>
             <a href="{% url 'schoolapp:register' %}"
                class="link-danger" style="color:white;">Register</a></p>
          </div>

        </form>
      </div>
    </div>
  </div>



</section>
{% endblock %}

schoolproject/templates/new_page.html
{% extends 'base.html' %}
{% block body %}
<div class="d-flex justify-content-center" style="padding-top:200px;">
    <a href="{% url 'schoolapp:form' %}"
                class="btn btn-success" style="color:white;">Click Here</a>
</div>

{% endblock %}

schoolproject/templates/onclick.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="">

        <p style="font-size:35px;text-align:center;padding-top:20%;"><i>Order Confirmed</i></p>

</div>
 <p style="text-align:center;">
    Go to home page
   <a href="{% url 'schoolapp:home' %}"><b>click</b></a>
    here.
  </p>
</body>
</html>

{% endblock %}

schoolproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<section class="vh-100 bg-image">

  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100" style="padding-top:20px;">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Registration</h2>

              <form  method="post">
                {% csrf_token %}
                <div class="form-outline mb-4">
                  <input type="text" id="form3Example1cg" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example1cg">User Name</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" id="form3Example3cg" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example3cg">Password</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" id="form3Example4cg" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example4cg"> Confirm Password</label>
                </div>




                <div class="d-flex justify-content-center">
                    <a href="{% url 'schoolapp:login' %}"
                class="btn btn-success" style="color:white;">Register</a>
                </div>



              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% for msg in messages %}
{{msg}}
{% endfor %}
{% endblock %}